// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class OneSignalPlayersUser
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string PlayerId { get; set; }

        public virtual AspNetUser User { get; set; }
    }
}