// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RIAT.Entity.Models
{
    [ModelMetadataType(typeof(Annotations.PacienteMetadata))]
    public partial class Paciente
    {
        
    }
}