// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class AlternativaAtendimento
    {
        public int Id { get; set; }
        public int IdAtendimento { get; set; }
        public int? IdAlternativaAdl { get; set; }
        public decimal Estado { get; set; }

        public virtual AlternativaAdl IdAlternativaAdlNavigation { get; set; }
        public virtual Atendimento IdAtendimentoNavigation { get; set; }
    }
}