// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RIAT.DAL.Entity.Models
{
    public partial class Atendimento
    {
        public Atendimento()
        {
            AlternativaAtendimentos = new HashSet<AlternativaAtendimento>();
            SintomaAtendimentos = new HashSet<SintomaAtendimento>();
        }

        public int Id { get; set; }
        public int TipaIdTipoAtendimento { get; set; }
        public DateTime AtenDtAgendamento { get; set; }
        public string AtenStAgendamento { get; set; }
        public DateTime? AtenDtCancelamento { get; set; }
        public string AtenTxMotivoCancelamento { get; set; }
        public DateTime? AtenDtRealizadaInicio { get; set; }
        public string AtenTxEvolucao { get; set; }
        public string AtenTxObservacoes { get; set; }
        public DateTime? AtenDtRealizadaFim { get; set; }
        public int PaciIdPaciente { get; set; }
        public int? ProfIdProfissional { get; set; }
        public string VideoConferencia { get; set; }
        public bool? ConfParticiPaciente { get; set; }
        public bool? ConfParticiProfissional { get; set; }
        public double? LatitudePlace { get; set; }
        public double? LongitudePlace { get; set; }
        public double? LatitudeCheckIn { get; set; }
        public double? LongitudeCheckIn { get; set; }
        public double? LatitudeCheckOut { get; set; }
        public double? LongitudeCheckOut { get; set; }        
        public string PostalCodePlace { get; set; }                
        public string StreetPlace { get; set; }
        [NotMapped]
        public string NeighborhoodPlace { get; set; }
        [NotMapped]
        public string CityPlace { get; set; }
        [NotMapped]
        public string StatePlace { get; set; }
        [NotMapped]
        public string CountryPlace { get; set; }        
        public string NumberPlace { get; set; }
        public string ComplementPlace { get; set; }
        
        public DateTime? AtenDtAgendamentoFim { get; set; }

        public virtual Paciente PaciIdPacienteNavigation { get; set; }
        public virtual Profissional ProfIdProfissionalNavigation { get; set; }
        public virtual TipoAtendimento TipaIdTipoAtendimentoNavigation { get; set; }
        public virtual ICollection<AlternativaAtendimento> AlternativaAtendimentos { get; set; }
        public virtual ICollection<SintomaAtendimento> SintomaAtendimentos { get; set; }
    }
}