// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class AtendimentoPlantao
    {
        public AtendimentoPlantao()
        {
            DataDesejada = new HashSet<DataDesejadum>();
        }

        public int Id { get; set; }
        public int? PaciIdPaciente { get; set; }
        public DateTime AtplDtPlantao { get; set; }
        public string AtplStAtendimento { get; set; }

        public virtual Paciente PaciIdPacienteNavigation { get; set; }
        public virtual ICollection<DataDesejadum> DataDesejada { get; set; }
    }
}