// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class DiaSemana
    {
        public DiaSemana()
        {
            DataDesejada = new HashSet<DataDesejadum>();
            ProfissionalHorarioDisponivels = new HashSet<ProfissionalHorarioDisponivel>();
        }

        public int Id { get; set; }
        public string DiseNmDiaSemana { get; set; }

        public virtual ICollection<DataDesejadum> DataDesejada { get; set; }
        public virtual ICollection<ProfissionalHorarioDisponivel> ProfissionalHorarioDisponivels { get; set; }
    }
}