// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class Doenca
    {
        public Doenca()
        {
            DoencaPacientes = new HashSet<DoencaPaciente>();
            Sintomas = new HashSet<Sintoma>();
        }

        public int Id { get; set; }
        public string DoenCodDoenca { get; set; }
        public string DoenNmHipotese { get; set; }

        public virtual ICollection<DoencaPaciente> DoencaPacientes { get; set; }
        public virtual ICollection<Sintoma> Sintomas { get; set; }
    }
}