// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class DoencaPaciente
    {
        public DoencaPaciente()
        {
            SintomaAtendimentos = new HashSet<SintomaAtendimento>();
        }

        public int Id { get; set; }
        public int DoenIdDoenca { get; set; }
        public int PaciIdPaciente { get; set; }

        public virtual Doenca DoenIdDoencaNavigation { get; set; }
        public virtual Paciente PaciIdPacienteNavigation { get; set; }
        public virtual ICollection<SintomaAtendimento> SintomaAtendimentos { get; set; }
    }
}