// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class Estado
    {
        public Estado()
        {
            Enderecos = new HashSet<Endereco>();
        }

        public string EstaIdSigla { get; set; }
        public string EstaNmEstado { get; set; }
        public int? PaisIdPais { get; set; }

        public virtual Pai PaisIdPaisNavigation { get; set; }
        public virtual ICollection<Endereco> Enderecos { get; set; }
    }
}