// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class Pai
    {
        public Pai()
        {
            Estados = new HashSet<Estado>();
        }

        public int PaisIdPais { get; set; }
        public string PaisNmPais { get; set; }

        public virtual ICollection<Estado> Estados { get; set; }
    }
}