// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class PessoaTelefone
    {
        public int Id { get; set; }
        public int PessIdPessoa { get; set; }
        public string PateCdDdi { get; set; }
        public string PateCdDdd { get; set; }
        public string PateNrTelefone { get; set; }
        public string PateStTipoTelefone { get; set; }

        public virtual Pessoa PessIdPessoaNavigation { get; set; }
    }
}