// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class ProfissionalEspecialidade
    {
        public int Id { get; set; }
        public int ProfIdProfissional { get; set; }
        public int EspeIdEspecialidade { get; set; }
        public string PresStGrauConhecimento { get; set; }
        public string PresStAtivo { get; set; }
        public DateTime PresDtAtivacao { get; set; }
        public DateTime? PresDtDesativacao { get; set; }
        public string PresCaminhoCertificacao { get; set; }

        public virtual Especialidade EspeIdEspecialidadeNavigation { get; set; }
    }
}