// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class ProfissionalHorarioDisponivel
    {
        public int Id { get; set; }
        public int ProfIdProfissional { get; set; }
        public int TurnIdTurno { get; set; }
        public int DiseIdDiaSemana { get; set; }

        public virtual DiaSemana DiseIdDiaSemanaNavigation { get; set; }
        public virtual Turno TurnIdTurnoNavigation { get; set; }
    }
}