// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class Profissional
    {
        public Profissional()
        {
            Atendimentos = new HashSet<Atendimento>();
            Pacientes = new HashSet<Paciente>();
        }

        public int IdPessoa { get; set; }
        public int TiprIdTipoProfissional { get; set; }
        public string ProfNrCrp { get; set; }
        public string ProfCdEPsi { get; set; }
        public string ProfTxMiniCurriculoInterno { get; set; }
        public string ProfTxMiniCurriculoPublico { get; set; }
        public string ProfStAtivo { get; set; }
        public DateTime ProfDtAtivacao { get; set; }
        public DateTime? ProfDtDesativacao { get; set; }

        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual TipoProfissional TiprIdTipoProfissionalNavigation { get; set; }
        public virtual ICollection<Atendimento> Atendimentos { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}