// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class SintomaAtendimento
    {
        public int Id { get; set; }
        public int DopaIdDoencaPaciente { get; set; }
        public int SintIdSintoma { get; set; }
        public short SidhCdPeso { get; set; }
        public int? IdAtendimento { get; set; }

        public virtual DoencaPaciente DopaIdDoencaPacienteNavigation { get; set; }
        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual Sintoma SintIdSintomaNavigation { get; set; }
    }
}