// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class Sintoma
    {
        public Sintoma()
        {
            SintomaAtendimentos = new HashSet<SintomaAtendimento>();
        }

        public int Id { get; set; }
        public string SintCodSintoma { get; set; }
        public string SintNomeSintoma { get; set; }
        public string SintDsSintoma { get; set; }
        public int DoenIdDoenca { get; set; }

        public virtual Doenca DoenIdDoencaNavigation { get; set; }
        public virtual ICollection<SintomaAtendimento> SintomaAtendimentos { get; set; }
    }
}