// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RIAT.DAL.Entity.Models
{
    public partial class TipoProfissional
    {
        public TipoProfissional()
        {
            Profissionals = new HashSet<Profissional>();
        }

        public int Id { get; set; }
        public string TiprNmTipoProfissional { get; set; }
        public string TiprDsTipoProfissional { get; set; }

        public virtual ICollection<Profissional> Profissionals { get; set; }
    }
}